<?xml version="1.0"?>
<package format="3">
  <name>e_stop_manager</name>
  <version>1.0.0</version>
  <description>The e_stop_manager package</description>

  <maintainer email="aljoscha.schmidt@tu-darmstadt.de">Aljoscha Schmidt</maintainer>

  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>std_msgs</depend>
  <depend>e_stop_manager_msgs</depend>
  <depend>rclcpp_components</depend>
  <test_depend>ros_testing</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
