# Each e-stop name in e_stop_topics needs to be in e_stop_list!

e_stop_list:
  - name: "ui_e_stop"
    value: false

e_stop_topics:
  - name: "/emergency_stop_software"
    e_stops:
      - "ui_e_stop"
